In [8]:
import pandas as pd
import numpy as np

In [3]:
x = np.arange(9.).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [5]:
np.where( x > 2 )

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [15]:
df1=pd.DataFrame({'key':['a','b','b'],'data1':range(3)})  
df2=pd.DataFrame({'key':['a','b','c'],'data2':range(3)}) 
df2

data2 key
0      0   a
1      1   b
2      2   c

In [18]:
data=pd.DataFrame([[1,2,3],[4,5,6]])
data

0  1  2
0  1  2  3
1  4  5  6

In [19]:
data.drop(0)

0  1  2
1  4  5  6

In [21]:
np.log1p(1)

0.6931471805599453

In [23]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)  
df.head()

a  b  c
d  1  2  3
e  4  5  6

In [26]:
print(df.ix[1])

a    4
b    5
c    6
Name: e, dtype: int64
